export const queries = [
    "Avengers",
    "Dil",
    "Inception",
    "Sholay",
    "Titanic",
    "Lagaan",
    "Jurassic Park",
    "Dilwale Dulhania Le Jayenge",
    "Interstellar",
    "Gone with the Wind",
    "Pulp Fiction",
    "Dangal",
    "The Dark Knight",
    "Golmaal",
    "The Godfather",
    "Jaws",
    "Chak De India",
    "Casablanca",
    "Shawshank Redemption",
    "Mughal-e-Azam",
    "Star Wars",
    "Baahubali",
    "Matrix",
    "Andaz Apna Apna",
    "E.T. the Extra-Terrestrial",
    "Kabhi Khushi Kabhie Gham",
    "The Lion King",
    "Rang De Basanti",
    "Forrest Gump",
    "Kuch Kuch Hota Hai",
    "Back to the Future",
    "Rocky",
    "Padosan",
    "The Matrix",
    "Mera Naam Joker",
    "The Silence of the Lambs",
    "Dhoom",
    "Memento",
    "Don",
    "Gladiator",
    "Chupke Chupke",
    "The Social Network",
    "Bajrangi Bhaijaan",
    "The Great Gatsby",
    "Jab We Met",
    "The Wizard of Oz",
    "Koi Mil Gaya",
    "The Shawshank Redemption",
    "Chennai Express",
    "The Terminator",
    "Finding Nemo",
    "Dil To Pagal Hai",
    "Avatar",
    "Lunchbox",
    "Fight Club",
    "Dhamaal",
    "The Revenant",
    "Zindagi Na Milegi Dobara",
    "Eternal Sunshine of the Spotless Mind",
    "Singin' in the Rain",
    "Phir Hera Pheri",
    "The Departed",
    "Jabariya Jodi",
    "The Princess Bride",
    "Bhaag Milkha Bhaag",
    "Groundhog Day",
    "Kabhi Alvida Naa Kehna",
    "The Shining",
    "Queen",
    "Deadpool",
    "Donnie Darko",
    "Main Hoon Na",
    "The Sound of Music",
    "Masaan",
    "Inglourious Basterds",
    "3 Idiots",
    "Coco",
    "Mughal-e-Azam",
    "The Breakfast Club",
    "Gadar: Ek Prem Katha",
    "The Grand Budapest Hotel",
    "Dear Zindagi",
    "Snatch",
    "Barfi!",
    "The Green Mile",
    "Tanu Weds Manu",
    "In Bruges",
    "Bajirao Mastani",
    "The Prestige",
    "Badlapur",
    "Shutter Island",
    "Lage Raho Munna Bhai",
    "La La Land",
    "Golmaal Again",
    "A Wednesday",
    "Jumanji",
    "Bareilly Ki Barfi",
    "The Hateful Eight",
    "Tamasha",
    "Harry Potter and the Sorcerer's Stone"
];